version: '3.8'

services:
  productapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEW_RELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}
    container_name: productapi
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NEW_RELIC_LICENSE_KEY=${NEWRELIC_LICENSE_KEY}
      # Keep app name consistent with Dockerfile
      - NEW_RELIC_APP_NAME=Product CRUD API
    networks:
      - productapi-network

networks:
  productapi-network:
    driver: bridge
